### ISSUE TITLE
Increate limit of token to 2**253

### ISSUE THREAD

**Issue by barryWhiteHat** [iden3/rollup#27]
Since we stopped putting hte token type on chain I don't think we need to limit the number of tokens like we do 

https://github.com/iden3/rollup/blob/master/contracts/Rollup.sol#L38

I think we can safely increase it to 2**253  without any per cost transaction increase. This does increase the cost of committing to fees tho so perhaps we should be lower than 2**253 but I feel its too high and will dicoragne token heavey contracts like from using rollup.

**Comment by krlosMata** [comment]
> Since we stopped putting hte token type on chain I don't think we need to limit the number of tokens like we do

Totally true

> I think we can safely increase it to 2**253 without any per cost transaction increase. This does increase the cost of committing to fees tho so perhaps we should be lower than 2**253 but I feel its too high and will dicoragne token heavey contracts like from using rollup.

We have to set a proper fee to insert tokens on rollup. Currently, there is a simple `fee*2` each time a token is inserted in order to prevent multiple non-useful token insertion, which could be too much. I was thinking on `fee ^ 1.2` increase

**Comment by barryWhiteHat** [comment]
I am unsure if we need to have the fee at all if we have 2**32 slots the gas limit will be enough to prevent people adding useless tokens.

**Comment by jbaylina** [comment]
I incremented to 32 bits.  The problem is that you need to select a coin and set a fee.  All this fee plan can be hashed, but it is s compromise.  You ether spend gas computing the hash, or adding more public params.   Right now we are useing 2 elements for selecting 16 17-bits coins and seting the fee.
We can do 32 bits with 3 elements (without a hash comput) or with one element but computing the hash onchain...

**Comment by barryWhiteHat** [comment]
2**32 is already enough that we would not need a limit on adding tokens in the evm. 

Will i close this issue or leave it open as a reminder ?
